title: Make ICP Great Again
description: MIGA DAO is an ICP community for discovering killer dAapps, sharing best practices and reviewing NNS proposals
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman